export const SCAVENGER_CLASSES: {[key: number]: string} = {
0: 'technologieundbrauchtum',
1: 'gemalde',
2: 'militariawaffen',
3: 'glas',
4: 'uhren',
5: 'histfotografie',
6: 'archaologie',
7: 'keramik',
8: 'graphik',
9: 'skulpturen',
10: 'textilienkostume',
11: 'schmuck',
12: 'edelmetall',
13: 'numismatik',
}
